// Reads the compiled HiveMarket artifact and writes its ABI into @hive/shared,
// so agents/indexer/dashboard bind to the contract without duplicating the ABI.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const target = resolve("../shared/src/abi.ts");

const market = JSON.parse(readFileSync(resolve("out/HiveMarket.sol/HiveMarket.json"), "utf8")).abi;
const reputation = JSON.parse(readFileSync(resolve("out/Reputation.sol/Reputation.json"), "utf8")).abi;

const contents = `// Generated by \`pnpm --filter @hive/contracts export-abi\`. Do not edit by hand.
export const hiveMarketAbi = ${JSON.stringify(market, null, 2)} as const;

export const reputationAbi = ${JSON.stringify(reputation, null, 2)} as const;
`;

writeFileSync(target, contents);
console.log(`Wrote ${market.length} market + ${reputation.length} reputation ABI entries to ${target}`);
